[project]
name = "note"
version = "0.2.1"
description = "Simple note capture"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb",
    "notedb",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
note = "note.main:main"
